title: Documentation UniShape CDR 2025 
description: Documentation de l'équipe UniShape pour la CDR 2025
theme: just-the-docs

url: https://unimakers.github.io/unishape-cdr2025-docs

aux_links:
  Template Repository: https://github.com/unimakers/unishape-cdr2025-docs
